# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Run Junit Tests
        run: mvn test
      - name: Check JavaDoc
        run: mvn checkstyle:checkstyle
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
      - name: Check for Javadoc warnings
        run: |
          if mvn javadoc:javadoc | grep -i "warning"; then
            echo "Javadoc warnings found, failing the build."
            exit 1
          else
            echo "No Javadoc warnings found."
          fi